### ISSUE TITLE
server crash when the pregen start  1.20.1

### ISSUE THREAD

**Issue by SPglouglou** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#43]
I have Chunk+Pregenerator-1.20-4.2.3 on forge 47.2.17.
And when I start generating a piece, the server instantly crashes with this error:
java.lang.NullPointerException: Cannot invoke "java.util.Optional.orElse(Object)" because the return value of "it.unimi.dsi.fastutil.longs.Long2ObjectMap.get(long)" is null

here is the crash log:
https://pastebin.com/7r1xNYNf

**Comment by Speiger** [comment]
That is lithiums poi optimizations crashing due to a memory leak I have fixed.

Simply disable the poi optimization or disable lithium until the pregeneration is done.

**Comment by SPglouglou** [comment]
thanks disable lithium solved this issue but now for all chunk generated it throw this error and stop the generation.


[Worker-Main1/ERROR] [minecraft/ThreadedLevelLightEngine]: Failed to light chunk [63, 56]
java.util.concurrent.CompletionException: java.lang.NullPointerException: No data is present for column: [46, 51]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:541) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:549) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:269) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:758) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.NullPointerException: No data is present for column: [46, 51]
	at net.minecraft.world.level.chunk.storage.SectionStorage.getNonEmptySections(SectionStorage.java:1175) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at net.minecraft.world.level.chunk.storage.SectionStorage.getNonEmptyPOISections(SectionStorage.java:1168) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at net.minecraft.world.level.chunk.storage.SectionStorage.getWithinChunkColumn(SectionStorage.java:1101) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at me.jellysquid.mods.lithium.common.world.interests.iterator.SphereChunkOrderedPoiSetSpliterator.tryAdvance(SphereChunkOrderedPoiSetSpliterator.java:51) ~[radium-mc1.20.1-0.12.2+git.5f80f74.jar%23644!/:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
	at fuzs.magnumtorch.handler.MobSpawningHandler.isSpawnCancelled(MobSpawningHandler.java:34) ~[MagnumTorch-v8.0.1-1.20.1-Forge.jar%23610!/:8.0.1]
	at fuzs.magnumtorch.handler.MobSpawningHandler.onLivingSpawn(MobSpawningHandler.java:23) ~[MagnumTorch-v8.0.1-1.20.1-Forge.jar%23610!/:8.0.1]
	at fuzs.puzzleslib.impl.event.ForgeEventInvokerRegistryImpl.lambda$register$45(ForgeEventInvokerRegistryImpl.java:368) ~[PuzzlesLib-v8.1.11-1.20.1-Forge.jar%23643!/:8.1.11]
	at fuzs.puzzleslib.api.event.v1.core.ForgeEventInvokerRegistry.lambda$register$0(ForgeEventInvokerRegistry.java:25) ~[PuzzlesLib-v8.1.11-1.20.1-Forge.jar%23643!/:8.1.11]
	at fuzs.puzzleslib.impl.event.ForgeEventInvokerRegistryImpl$ForgeEventInvoker.lambda$register$1(ForgeEventInvokerRegistryImpl.java:760) ~[PuzzlesLib-v8.1.11-1.20.1-Forge.jar%23643!/:8.1.11]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157538_(PersistentEntitySectionManager.java:79) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157604_(PersistentEntitySectionManager.java:121) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at net.minecraft.world.entity.EntityType$1.m_147060_(EntityType.java:585) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.world.entity.EntityType.m_20645_(EntityType.java:563) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at net.minecraft.world.entity.EntityType$1.m_147056_(EntityType.java:584) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) ~[?:?]
	at net.minecraft.world.entity.EntityType$1.tryAdvance(EntityType.java:583) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at java.util.Spliterator.forEachRemaining(Spliterator.java:332) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157559_(PersistentEntitySectionManager.java:120) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at net.minecraft.server.level.ServerLevel.m_143327_(ServerLevel.java:1434) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at net.minecraft.server.level.ChunkMap.m_143064_(ChunkMap.java:690) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at net.minecraft.server.level.ChunkMap.m_214898_(ChunkMap.java:707) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at net.minecraft.world.level.chunk.LevelChunk.m_62952_(LevelChunk.java:438) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at net.minecraft.server.level.ChunkMap.mixinextras$bridge$m_62952_$157(ChunkMap.java) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at net.minecraft.server.level.ChunkMap.wrapOperation$zdd000$modernfix$setCurrentLoadingThenPostLoad(ChunkMap.java:1905) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at net.minecraft.server.level.ChunkMap.m_214854_(ChunkMap.java:715) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-6.0.8.jar%2377!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar%2377!/:?]
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-6.0.8.jar%2377!/:?]
	at net.minecraft.server.level.ChunkMap.m_287044_(ChunkMap.java:699) ~[server-1.20.1-20230612.114412-srg.jar%23743!/:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	... 14 more

**Comment by Speiger** [comment]
``at me.jellysquid.mods.lithium.common.world.interests.iterator.SphereChunkOrderedPoiSetSpliterator.tryAdvance(SphereChunkOrderedPoiSetSpliterator.java:51) ~[radium-mc1.20.1-0.12.2+git.5f80f74.jar%23644!/:?]
``

That error still shows lithiums poi optimization is still enabled
