### ISSUE TITLE
Chunk Pregen crashing the server after around 5-10k chunks generated, sometimes earlier

### ISSUE THREAD

**Issue by chilletize** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#77]
Seems to crash for no apparent reason, tried removing and adding mods but nothing changes, sometimes it crashes pointing to another mod for no reason after removing it, it still crashes sometimes blaming other completely unrelated mods.

```
Time: 7/21/24 6:41 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/world/World$2
	at net.minecraft.world.World.func_190524_a(World.java:557)
	at net.minecraft.world.World.func_175685_c(World.java:492)
	at net.minecraft.world.World.func_175722_b(World.java:440)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:381)
	at net.minecraft.world.World.func_180501_a(World.java:361)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:129)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:129)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:129)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:129)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:129)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:133)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:153)
	at net.minecraft.world.World.func_189507_a(World.java:2682)
	at net.minecraft.world.gen.feature.WorldGenLiquids.func_180709_b(WorldGenLiquids.java:88)
	at net.minecraft.world.biome.BiomeDecorator.func_150513_a(BiomeDecorator.java:363)
	at net.minecraft.world.biome.BiomeDecorator.func_180292_a(BiomeDecorator.java:88)
	at net.minecraft.world.biome.Biome.func_180624_a(Biome.java:225)
	at net.minecraft.world.biome.BiomeForest.func_180624_a(BiomeForest.java:110)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:464)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:980)
	at pregenerator.impl.processor.generator.ChunkEntry.populate(ChunkEntry.java:179)
	at pregenerator.impl.processor.generator.ChunkEntry.process(ChunkEntry.java:147)
	at pregenerator.impl.processor.generator.ChunkEntry.tick(ChunkEntry.java:69)
	at pregenerator.impl.processor.generator.ChunkProcess.tick(ChunkProcess.java:125)
	at pregenerator.impl.processor.generator.ChunkProcessor.onTickEnd(ChunkProcessor.java:100)
	at pregenerator.impl.processor.ServerManager.onServerTickEvent(ServerManager.java:45)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1279_ServerManager_onServerTickEvent_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

No Mixin Metadata is found in the Stacktrace.

```

**Comment by Speiger** [comment]
Since i am supporting 1.7.10->1.21 atm it would be nice which mc version you are speaking of.
Also which version of the mod are you running?

**Comment by chilletize** [comment]
I am using 1.12.2, sorry for not mentioning. Here it crashed again but this time it was a shorter crash log, do you want a full log? The mod version is latest (4.4.8). It's rare for devs to support older versions or so many, so thanks for doing that!

```
Time: 7/21/24 6:59 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/world/World$2
	at net.minecraft.world.World.func_190524_a(World.java:557)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at net.minecraft.world.World.func_175722_b(World.java:440)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:381)
	at net.minecraft.world.World.func_180501_a(World.java:361)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:153)
	at net.minecraft.world.World.func_189507_a(World.java:2682)
	at net.minecraft.world.gen.feature.WorldGenLiquids.func_180709_b(WorldGenLiquids.java:88)
	at net.minecraft.world.biome.BiomeDecorator.func_150513_a(BiomeDecorator.java:363)
	at net.minecraft.world.biome.BiomeDecorator.func_180292_a(BiomeDecorator.java:88)
	at net.minecraft.world.biome.Biome.func_180624_a(Biome.java:225)
	at net.minecraft.world.biome.BiomeHills.func_180624_a(BiomeHills.java:41)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:464)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:980)
	at pregenerator.impl.processor.generator.ChunkEntry.populate(ChunkEntry.java:179)
	at pregenerator.impl.processor.generator.ChunkEntry.process(ChunkEntry.java:147)
	at pregenerator.impl.processor.generator.ChunkEntry.tick(ChunkEntry.java:69)
	at pregenerator.impl.processor.generator.ChunkProcess.tick(ChunkProcess.java:125)
	at pregenerator.impl.processor.generator.ChunkProcessor.onTickEnd(ChunkProcessor.java:100)
	at pregenerator.impl.processor.ServerManager.onServerTickEvent(ServerManager.java:45)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1282_ServerManager_onServerTickEvent_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Speiger** [comment]
@chilletize could you validate that it works for you with just chunkpregen & its dependencies installed?
Because this looks like a incompat with another mod.

If not then it looks like that you may have a corrupted jar. But i will validate it on my side too just in case.

Update:
I have tried chunkpregen alone and it works just fine.
And to be extra sure i redownloaded the mod from curseforge.

**Comment by chilletize** [comment]
Are there any known incompatibilities? It does work on its own but I can't wrap my head around what causes this issue as no specific mod is mentioned. I'll upload the whole log if you need. I removed Rats mod and Recurrent Complex including some others to test if the structures are causing it including Traverse which is biomes but none fixed it.
[latest.log](https://github.com/user-attachments/files/16325400/latest.log)

**Comment by Speiger** [comment]
@chilletize have you looked at #1 ?
I would suggest you try divide and conker.
Half the mods and check if it still crashes until you get down to the mod that causes it.

**Comment by chilletize** [comment]
There's quite a few mods to do that but I'll try, hopefully I can find it early, do you have any idea what mod could cause this? I don't understand anything ab the crash report so I'm lost haha

**Comment by Speiger** [comment]
The crashlog is forge not being able to access a certain subclass in the code.
So it can only be an optimization mod from my best guess.
But that doesn't have to be true ^^"

**Comment by chilletize** [comment]
Are you aware of any incompat with Rats mod or Roguelike? I got crash with rats and pregenerator first and then roguelike and pregen:

```
	at net.minecraft.world.World.func_180495_p(World.java:911)
	at greymerk.roguelike.worldgen.WorldEditor.getBlock(WorldEditor.java:137)
	at greymerk.roguelike.worldgen.WorldEditor.setBlock(WorldEditor.java:49)
	at greymerk.roguelike.worldgen.WorldEditor.setBlock(WorldEditor.java:80)
	at greymerk.roguelike.worldgen.MetaBlock.set(MetaBlock.java:90)
	at greymerk.roguelike.worldgen.shapes.RectSolid.fill(RectSolid.java:30)
	at greymerk.roguelike.worldgen.shapes.RectSolid.fill(RectSolid.java:24)
	at greymerk.roguelike.dungeon.DungeonTunnel.construct(DungeonTunnel.java:79)
	at greymerk.roguelike.dungeon.DungeonGenerator.generate(DungeonGenerator.java:90)
	at greymerk.roguelike.dungeon.Dungeon.generate(Dungeon.java:128)
	at greymerk.roguelike.dungeon.Dungeon.generateNear(Dungeon.java:121)
	at greymerk.roguelike.dungeon.Dungeon.spawnInChunk(Dungeon.java:192)
	at greymerk.roguelike.DungeonGenerator.generate(DungeonGenerator.java:20)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:980)
	at pregenerator.impl.processor.generator.ChunkEntry.populate(ChunkEntry.java:179)
	at pregenerator.impl.processor.generator.ChunkEntry.process(ChunkEntry.java:147)
	at pregenerator.impl.processor.generator.ChunkEntry.tick(ChunkEntry.java:69)
	at pregenerator.impl.processor.generator.ChunkProcess.tick(ChunkProcess.java:125)
	at pregenerator.impl.processor.generator.ChunkProcessor.onTickEnd(ChunkProcessor.java:100)
	at pregenerator.impl.processor.ServerManager.onServerTickEvent(ServerManager.java:45)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1201_ServerManager_onServerTickEvent_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
```

```
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:153)
	at net.minecraft.world.World.func_189507_a(World.java:2682)
	at net.minecraft.world.gen.feature.WorldGenLiquids.func_180709_b(WorldGenLiquids.java:88)
	at net.minecraft.world.biome.BiomeDecorator.func_150513_a(BiomeDecorator.java:363)
	at net.minecraft.world.biome.BiomeDecorator.func_180292_a(BiomeDecorator.java:88)
	at net.minecraft.world.biome.Biome.func_180624_a(Biome.java:225)
	at net.minecraft.world.biome.BiomeDesert.func_180624_a(BiomeDesert.java:48)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:464)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.ChunkCache.<init>(ChunkCache.java:37)
	at net.minecraft.pathfinding.PathNavigate.func_179680_a(SourceFile:113)
	at net.minecraft.pathfinding.PathNavigateGround.func_179680_a(SourceFile:65)
	at com.github.alexthe666.rats.server.entity.ai.RatPathNavigateGround.func_179680_a(RatPathNavigateGround.java:48)
	at net.minecraft.pathfinding.PathNavigate.func_75488_a(SourceFile:93)
	at net.minecraft.pathfinding.PathNavigate.func_75492_a(SourceFile:143)
	at com.github.alexthe666.rats.server.entity.ai.RatPathNavigateGround.func_75492_a(RatPathNavigateGround.java:72)
	at net.minecraft.entity.ai.EntityAIWander.func_75249_e(SourceFile:65)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:102)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at com.github.alexthe666.rats.server.entity.EntityRat.func_70636_d(EntityRat.java:884)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
```

Removed both now waiting for a possible 3rd crash/mod cause.

**Comment by chilletize** [comment]
I ran out of mods to remove or test and I have no idea what causes this, also submitted a post on Minecraft Forums, thank you so much for your help. The mods above probably have no conflict and it just blames random mods, my most recent crash mentioned RecurrentComplex and IVToolkit, removed them then crashed again with the short crash log I submitted above. Literally no idea what this could be.

Found something in my crash report not sure if it means something but sounds important, the last line of this:

```
-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_411, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 11162016800 bytes (10644 MB) / 18942525440 bytes (18065 MB) up to 22906667008 bytes (21845 MB)
	JVM Flags: 2 total; -Xmx24G -Xms8G
	IntCache: cache: 1, tcache: 1, allocated: 14, tallocated: 94
	FML: ~~ERROR~~ NoClassDefFoundError: net/minecraftforge/common/util/TextTable$1
```
