### ISSUE TITLE
[1.7.10] NoSuchMethodError when loading into GTNH

### ISSUE THREAD

**Issue by mainrs** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#82]
Running GTNH 2.6.1. I manually added the mod to pregen my world. However, I get the following stacktrace when launching the instance ([full stacktrace](https://mclo.gs/A6vv0yq)): 

```
[21:46:28] [Client thread/ERROR] [FML]: Caught exception from carbonconfig
java.lang.NoSuchMethodError: 'void speiger.src.collections.objects.maps.impl.hash.Object2ObjectOpenHashMap$MapEntry.set(int)'
	at RFB-Launch//speiger.src.collections.objects.maps.impl.hash.Object2ObjectLinkedOpenHashMap$MapEntrySet.fastForEach(Object2ObjectLinkedOpenHashMap.java:604) ~[Object2ObjectLinkedOpenHashMap$MapEntrySet.class:1.7.10-1.2.4]
	at RFB-Launch//speiger.src.collections.objects.utils.maps.Object2ObjectMaps.fastForEach(Object2ObjectMaps.java:83) ~[Object2ObjectMaps.class:1.7.10-1.2.4]
	at RFB-Launch//carbonconfiglib.config.ConfigSection.serialize(ConfigSection.java:307) ~[ConfigSection.class:1.7.10-1.2.4]
	at RFB-Launch//carbonconfiglib.config.ConfigSection.serialize(ConfigSection.java:286) ~[ConfigSection.class:1.7.10-1.2.4]
	at RFB-Launch//carbonconfiglib.config.Config.serialize(Config.java:109) ~[Config.class:1.7.10-1.2.4]
	at RFB-Launch//carbonconfiglib.config.ConfigHandler.save(ConfigHandler.java:372) ~[ConfigHandler.class:1.7.10-1.2.4]
	at RFB-Launch//carbonconfiglib.config.ConfigHandler.save(ConfigHandler.java:360) ~[ConfigHandler.class:1.7.10-1.2.4]
	at RFB-Launch//carbonconfiglib.config.ConfigHandler.load(ConfigHandler.java:191) ~[ConfigHandler.class:1.7.10-1.2.4]
	at RFB-Launch//carbonconfiglib.config.ConfigHandler.register(ConfigHandler.java:162) ~[ConfigHandler.class:1.7.10-1.2.4]
	at RFB-Launch//carbonconfiglib.CarbonConfig.onPreInit(CarbonConfig.java:105) ~[CarbonConfig.class:1.7.10-1.2.4]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at RFB-Launch//cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at RFB-System//com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at RFB-System//com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at RFB-System//com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at RFB-System//com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at RFB-System//com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at RFB-Launch//cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at RFB-Launch//cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
...
```

Any idea why this might happen? I also tried downgrading (randomly) the lib and chunk-pregen. But that didn't work. It seems like a version mismatch to me.

I am running chunk-pregen v4.4.9 and carbon config 1.2.4.

**Comment by Speiger** [comment]
@mainrs https://github.com/embeddedt/ArchaicFix/issues/123

**Comment by mainrs** [comment]
ArchaicFix 0.7.4 and CarbonConfig 1.2.4 worked for me, thank you!

**Comment by Speiger** [comment]
@mainrs no problem :)
